services:
  mariadb:
    image: mariadb:11.6.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password1!
      MYSQL_DATABASE: omni
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', '/usr/local/bin/healthcheck.sh', '--innodb_initialized']
      start_period: 5s
      timeout: 5s
      interval: 5s
      retries: 5

  migrate:
    image: migrate/migrate:latest
    depends_on:
      mariadb:
        condition: service_healthy
    entrypoint: [
      "sh", "-c",
      "migrate -path=/migrations -database 'mysql://root:Password1!@tcp(mariadb:3306)/omni' up"
    ]
    volumes:
      - ./db/migrations:/migrations

  omni_view:
    build:
      context: ./
      dockerfile: cmd/OmniView/Dockerfile
    depends_on:
      - omni_read
      - omni_write
      - omni_auth
    environment:
      VERBOSE: "true"
      HOST: "localhost"
      PORT: "80"
      WRITE_API_URL: "http://omni_write:80"
      READ_API_URL: "http://omni_read:80"
      AUTH_API_URL: "http://omni_auth:80"
      JWT_SECRET: "omni-super-secret-key"
    ports:
      - "8080:80"  # Adjust port mapping as needed

  omni_read:
    build:
      context: ./
      dockerfile: cmd/OmniRead/Dockerfile
    depends_on:
      - mariadb
    environment:
      VERBOSE: "true"
      HOST: "localhost"
      PORT: "80"
      DATA_SOURCE_NAME: "root:Password1!@tcp(mariadb:3306)/omni?parseTime=true"
      CONNECTION_MAX_LIFETIME: "3"
      MAX_OPEN_CONNECTIONS: "10"
      MAX_IDLE_CONNECTIONS: "10"
    ports:
      - "8081:80"  # Adjust port mapping as needed

  omni_auth:
    build:
      context: ./
      dockerfile: cmd/OmniAuth/Dockerfile
    depends_on:
      - mariadb
    environment:
      VERBOSE: "true"
      HOST: "localhost"
      PORT: "80"
      DATA_SOURCE_NAME: "root:Password1!@tcp(mariadb:3306)/omni?parseTime=true"
      CONNECTION_MAX_LIFETIME: "3"
      MAX_OPEN_CONNECTIONS: "10"
      MAX_IDLE_CONNECTIONS: "10"
      JWT_SECRET: "omni-super-secret-key"
      NODE_NAME: "dockercompose"
    ports:
      - "8082:80"

  omni_write:
    build:
      context: ./
      dockerfile: cmd/OmniWrite/Dockerfile
    depends_on:
      - mariadb
    environment:
      VERBOSE: "true"
      HOST: "localhost"
      PORT: "80"
      DATA_SOURCE_NAME: "root:Password1!@tcp(mariadb:3306)/omni?parseTime=true"
      CONNECTION_MAX_LIFETIME: "3"
      MAX_OPEN_CONNECTIONS: "10"
      MAX_IDLE_CONNECTIONS: "10"
      JWT_SECRET: "omni-super-secret-key"
      NODE_NAME: "dockercompose"
    ports:
      - "8083:80"

volumes:
  mariadb_data:
