# Server configuration
server:
  host: "localhost"
  port: 8080

# Database configuration
database:
  driverName: "mysql"
  dataSourceName: "root:Password1!@tcp(localhost)/omni?parseTime=true"
  ConnMaxLifetime: 3
  MaxIdleConns: 10
  MaxOpenConns: 10
