// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: comment.sql

package storage

import (
	"context"
	"time"
)

const createComment = `-- name: CreateComment :exec
INSERT INTO Comments (id, post_id, user_id, content, created_at) VALUES (?, ?, ?, ?, ?)
`

type CreateCommentParams struct {
	ID        int64     `json:"id"`
	PostID    int64     `json:"post_id"`
	UserID    int64     `json:"user_id"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) error {
	_, err := q.exec(ctx, q.createCommentStmt, createComment,
		arg.ID,
		arg.PostID,
		arg.UserID,
		arg.Content,
		arg.CreatedAt,
	)
	return err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM Comments WHERE id = ?
`

func (q *Queries) DeleteComment(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteCommentStmt, deleteComment, id)
	return err
}

const findCommentAndUserByID = `-- name: FindCommentAndUserByID :one
SELECT comments.id, comments.post_id, comments.user_id, comments.content, comments.created_at, users.id, users.username FROM Comments 
INNER JOIN Users 
ON Comments.user_id = Users.id 
WHERE Comments.id = ?
`

type FindCommentAndUserByIDRow struct {
	Comment Comment `json:"comment"`
	User    User    `json:"user"`
}

func (q *Queries) FindCommentAndUserByID(ctx context.Context, id int64) (FindCommentAndUserByIDRow, error) {
	row := q.queryRow(ctx, q.findCommentAndUserByIDStmt, findCommentAndUserByID, id)
	var i FindCommentAndUserByIDRow
	err := row.Scan(
		&i.Comment.ID,
		&i.Comment.PostID,
		&i.Comment.UserID,
		&i.Comment.Content,
		&i.Comment.CreatedAt,
		&i.User.ID,
		&i.User.Username,
	)
	return i, err
}

const findCommentsAndUserByPostIDPaged = `-- name: FindCommentsAndUserByPostIDPaged :many
SELECT comments.id, comments.post_id, comments.user_id, comments.content, comments.created_at, users.id, users.username FROM Comments 
INNER JOIN Users 
ON Comments.user_id = Users.id 
WHERE Comments.post_id = ? AND Comments.created_at > ? 
ORDER BY Comments.created_at ASC
LIMIT ?
`

type FindCommentsAndUserByPostIDPagedParams struct {
	PostID       int64     `json:"post_id"`
	CreatedAfter time.Time `json:"created_after"`
	Limit        int32     `json:"limit"`
}

type FindCommentsAndUserByPostIDPagedRow struct {
	Comment Comment `json:"comment"`
	User    User    `json:"user"`
}

func (q *Queries) FindCommentsAndUserByPostIDPaged(ctx context.Context, arg FindCommentsAndUserByPostIDPagedParams) ([]FindCommentsAndUserByPostIDPagedRow, error) {
	rows, err := q.query(ctx, q.findCommentsAndUserByPostIDPagedStmt, findCommentsAndUserByPostIDPaged, arg.PostID, arg.CreatedAfter, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindCommentsAndUserByPostIDPagedRow
	for rows.Next() {
		var i FindCommentsAndUserByPostIDPagedRow
		if err := rows.Scan(
			&i.Comment.ID,
			&i.Comment.PostID,
			&i.Comment.UserID,
			&i.Comment.Content,
			&i.Comment.CreatedAt,
			&i.User.ID,
			&i.User.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComment = `-- name: UpdateComment :exec
UPDATE Comments SET content=? WHERE id=?
`

type UpdateCommentParams struct {
	Content string `json:"content"`
	ID      int64  `json:"id"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) error {
	_, err := q.exec(ctx, q.updateCommentStmt, updateComment, arg.Content, arg.ID)
	return err
}
