apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-readapi-service
  labels:
    app: {{ .Chart.Name }}-readapi
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Chart.Name }}-readapi
