apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-viewapi-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}-viewapi
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Chart.Name }}-viewapi
