omniread:
  replicaCount: 5
  image:
    repository: raspidb.local/harrydayexe/omniread
    tag: latest
    pullPolicy: Always

omniwrite:
  replicaCount: 3
  image:
    repository: raspidb.local/harrydayexe/omniwrite
    tag: latest
    pullPolicy: Always

service:
  host: 192.168.1.212
  port: 80
  targetPort: 80

database:
  host: 192.168.1.191
  username: user
  password: Password1!
  database: omni

gateway:
  gatewayClassName: nginx

namespace: omni
