omniread:
  replicaCount: 5
  verbose: true
  image:
    repository: raspidb.local/harrydayexe/omniread
    tag: latest
    pullPolicy: Always

omniwrite:
  replicaCount: 3
  verbose: true
  image:
    repository: raspidb.local/harrydayexe/omniwrite
    tag: latest
    pullPolicy: Always

omniauth:
  replicaCount: 1
  verbose: true
  image:
    repository: raspidb.local/harrydayexe/omniauth
    tag: latest
    pullPolicy: Always

omniview:
  replicaCount: 5
  verbose: true
  image:
    repository: raspidb.local/harrydayexe/omniview
    tag: latest
    pullPolicy: Always

service:
  host: 192.168.1.212
  port: 80
  targetPort: 80

database:
  host: 192.168.1.191
  username: user
  password: Password1!
  database: omni

gateway:
  gatewayClassName: nginx

namespace: omni
# This should be stored as a secret but I don't have time to set that up
jwt: omni-super-secret-key
